### ISSUE TITLE
advice

### ISSUE THREAD

**Issue by vincentDcmps** [khuedoan/dotfiles#11]
Hello,

I take a look on your nvim config to create mine but  have a litle question,
when I edit all my yaml file the ansiblels server is always active  for kubernetes file for example. 
do you meet this too? 
ansible lsp server pop some playbook error but is not justified because my file is not an playbook.

**Comment by khuedoan** [comment]
I don't have the playbook errors in Kubernetes manifests, here's my `:LspInfo` on a Kubernetes manifest (it does have `ansiblels` tho):

![image](https://user-images.githubusercontent.com/27996771/152665384-69487296-b0b2-4e19-9ffc-2036a51ac2dc.png)

**Comment by vincentDcmps** [comment]
here exact message  if you have an idea
![Capture d’écran du 2022-02-06 09-19-45](https://user-images.githubusercontent.com/29679418/152672895-e60fee59-3dc5-4ea9-a9c0-2607eab06b10.png)

**Comment by khuedoan** [comment]
Do you have the `:LspInfo` output?

**Comment by vincentDcmps** [comment]
![Capture d’écran du 2022-02-06 09-49-57](https://user-images.githubusercontent.com/29679418/152673833-5e778b33-8fd0-4801-8d2c-1bc5e3517e9f.png)
here my config
https://git.ducamps.win/vincent/conf2/src/branch/master/nvim/.config/nvim/init.lua

**Comment by khuedoan** [comment]
I don't have the same problem, does it have the same issue if you use the same config as mine?

**Comment by vincentDcmps** [comment]
yes I have copy your init.lua and get same message

**Comment by khuedoan** [comment]
Strange, I have no idea then :stuck_out_tongue:

**Comment by vincentDcmps** [comment]
do you have ansible-lint install on your computer?
I notice if I uninstall ansible-lint I don't have this message

**Comment by khuedoan** [comment]
I don't but you're right, if I install ansible-lint it has the same problem, but usually I just let my CI to run the lint instead, for example:

https://github.com/khuedoan/homelab/blob/363b3fda95b1c7da5f6dd2843b77aa428f0c214e/.tekton/tasks/lint.yaml#L9-L15

**Comment by vincentDcmps** [comment]
CI do that too, but sometime I check on my computer, thanks for your help
